// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProductsAPI.Data;

#nullable disable

namespace ProductsAPI.Migrations
{
    [DbContext(typeof(ProductsAPIContext))]
    [Migration("20240215185511_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ProductsAPI.Models.Product", b =>
                {
                    b.Property<int>("ProductID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProductID"));

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("ListPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ProductCategoryID")
                        .HasColumnType("int");

                    b.Property<string>("ProductNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Size")
                        .HasColumnType("int");

                    b.Property<decimal>("StandardCost")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Weight")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("ProductID");

                    b.HasIndex("ProductCategoryID");

                    b.ToTable("Product");

                    b.HasData(
                        new
                        {
                            ProductID = 1,
                            Color = "Red",
                            ListPrice = 337.22m,
                            Name = "LL Road Frame - Red, 44",
                            ProductCategoryID = 18,
                            ProductNumber = "FR-R38R-44",
                            Size = 44,
                            StandardCost = 187.1571m,
                            Weight = 1052.33m
                        },
                        new
                        {
                            ProductID = 2,
                            Color = "Red",
                            ListPrice = 337.22m,
                            Name = "LL Road Frame - Red, 48",
                            ProductCategoryID = 18,
                            ProductNumber = "FR-R38R-48",
                            Size = 48,
                            StandardCost = 187.1571m,
                            Weight = 1070.47m
                        },
                        new
                        {
                            ProductID = 3,
                            Color = "Red",
                            ListPrice = 337.22m,
                            Name = "LL Road Frame - Red, 52",
                            ProductCategoryID = 18,
                            ProductNumber = "FR-R38R-52",
                            Size = 52,
                            StandardCost = 187.1571m,
                            Weight = 1088.62m
                        },
                        new
                        {
                            ProductID = 4,
                            Color = "Red",
                            ListPrice = 337.22m,
                            Name = "LL Road Frame - Red, 58",
                            ProductCategoryID = 18,
                            ProductNumber = "FR-R38R-58",
                            Size = 58,
                            StandardCost = 187.1571m,
                            Weight = 1115.83m
                        },
                        new
                        {
                            ProductID = 5,
                            Color = "Red",
                            ListPrice = 337.22m,
                            Name = "LL Road Frame - Red, 60",
                            ProductCategoryID = 18,
                            ProductNumber = "FR-R38R-60",
                            Size = 60,
                            StandardCost = 187.1571m,
                            Weight = 1124.9m
                        },
                        new
                        {
                            ProductID = 6,
                            Color = "Red",
                            ListPrice = 337.22m,
                            Name = "LL Road Frame - Red, 62",
                            ProductCategoryID = 18,
                            ProductNumber = "FR-R38R-62",
                            Size = 62,
                            StandardCost = 187.1571m,
                            Weight = 1133.98m
                        },
                        new
                        {
                            ProductID = 7,
                            Color = "Red",
                            ListPrice = 594.83m,
                            Name = "ML Road Frame - Red, 44",
                            ProductCategoryID = 18,
                            ProductNumber = "FR-R72R-44",
                            Size = 44,
                            StandardCost = 352.1394m,
                            Weight = 1006.97m
                        },
                        new
                        {
                            ProductID = 8,
                            Color = "Red",
                            ListPrice = 594.83m,
                            Name = "ML Road Frame - Red, 48",
                            ProductCategoryID = 18,
                            ProductNumber = "FR-R72R-48",
                            Size = 48,
                            StandardCost = 352.1394m,
                            Weight = 1025.11m
                        },
                        new
                        {
                            ProductID = 9,
                            Color = "Red",
                            ListPrice = 594.83m,
                            Name = "ML Road Frame - Red, 52",
                            ProductCategoryID = 18,
                            ProductNumber = "FR-R72R-52",
                            Size = 52,
                            StandardCost = 352.1394m,
                            Weight = 1043.26m
                        },
                        new
                        {
                            ProductID = 10,
                            Color = "Red",
                            ListPrice = 594.83m,
                            Name = "ML Road Frame - Red, 58",
                            ProductCategoryID = 18,
                            ProductNumber = "FR-R72R-58",
                            Size = 58,
                            StandardCost = 352.1394m,
                            Weight = 1070.47m
                        },
                        new
                        {
                            ProductID = 11,
                            Color = "Red",
                            ListPrice = 594.83m,
                            Name = "ML Road Frame - Red, 60",
                            ProductCategoryID = 18,
                            ProductNumber = "FR-R72R-60",
                            Size = 60,
                            StandardCost = 352.1394m,
                            Weight = 1079.54m
                        },
                        new
                        {
                            ProductID = 12,
                            Color = "Silver",
                            ListPrice = 1364.5m,
                            Name = "HL Mountain Frame - Silver, 44",
                            ProductCategoryID = 16,
                            ProductNumber = "FR-M94S-44",
                            Size = 44,
                            StandardCost = 706.811m,
                            Weight = 1251.91m
                        },
                        new
                        {
                            ProductID = 13,
                            Color = "Silver",
                            ListPrice = 1364.5m,
                            Name = "HL Mountain Frame - Silver, 48",
                            ProductCategoryID = 16,
                            ProductNumber = "FR-M94S-52",
                            Size = 48,
                            StandardCost = 706.811m,
                            Weight = 1270.05m
                        },
                        new
                        {
                            ProductID = 14,
                            Color = "Black",
                            ListPrice = 1349.6m,
                            Name = "HL Mountain Frame - Black, 44",
                            ProductCategoryID = 16,
                            ProductNumber = "FR-M94B-44",
                            Size = 44,
                            StandardCost = 699.0928m,
                            Weight = 1251.91m
                        },
                        new
                        {
                            ProductID = 15,
                            Color = "Black",
                            ListPrice = 1349.6m,
                            Name = "HL Mountain Frame - Black, 48",
                            ProductCategoryID = 16,
                            ProductNumber = "FR-M94B-48",
                            Size = 48,
                            StandardCost = 699.0928m,
                            Weight = 1270.05m
                        },
                        new
                        {
                            ProductID = 16,
                            Color = "Red",
                            ListPrice = 3578.27m,
                            Name = "Road-150 Red, 62",
                            ProductCategoryID = 6,
                            ProductNumber = "BK-R93R-62",
                            Size = 62,
                            StandardCost = 2171.2942m,
                            Weight = 6803.85m
                        },
                        new
                        {
                            ProductID = 17,
                            Color = "Red",
                            ListPrice = 3578.27m,
                            Name = "Road-150 Red, 44",
                            ProductCategoryID = 6,
                            ProductNumber = "BK-R93R-44",
                            Size = 44,
                            StandardCost = 2171.2942m,
                            Weight = 6245.93m
                        },
                        new
                        {
                            ProductID = 18,
                            Color = "Red",
                            ListPrice = 3578.27m,
                            Name = "Road-150 Red, 48",
                            ProductCategoryID = 6,
                            ProductNumber = "BK-R93R-48",
                            Size = 48,
                            StandardCost = 2171.2942m,
                            Weight = 6409.23m
                        },
                        new
                        {
                            ProductID = 19,
                            Color = "Red",
                            ListPrice = 3578.27m,
                            Name = "Road-150 Red, 52",
                            ProductCategoryID = 6,
                            ProductNumber = "BK-R93R-52",
                            Size = 52,
                            StandardCost = 2171.2942m,
                            Weight = 6540.77m
                        },
                        new
                        {
                            ProductID = 20,
                            Color = "Red",
                            ListPrice = 3578.27m,
                            Name = "Road-150 Red, 56",
                            ProductCategoryID = 6,
                            ProductNumber = "BK-R93R-56",
                            Size = 56,
                            StandardCost = 2171.2942m,
                            Weight = 6658.7m
                        },
                        new
                        {
                            ProductID = 21,
                            Color = "Red",
                            ListPrice = 1457.99m,
                            Name = "Road-450 Red, 58",
                            ProductCategoryID = 6,
                            ProductNumber = "BK-R68R-58",
                            Size = 58,
                            StandardCost = 884.7083m,
                            Weight = 8069.37m
                        },
                        new
                        {
                            ProductID = 22,
                            Color = "Red",
                            ListPrice = 1457.99m,
                            Name = "Road-450 Red, 60",
                            ProductCategoryID = 6,
                            ProductNumber = "BK-R68R-60",
                            Size = 60,
                            StandardCost = 884.7083m,
                            Weight = 8119.26m
                        },
                        new
                        {
                            ProductID = 23,
                            Color = "Red",
                            ListPrice = 1457.99m,
                            Name = "Road-450 Red, 44",
                            ProductCategoryID = 6,
                            ProductNumber = "BK-R68R-44",
                            Size = 44,
                            StandardCost = 884.7083m,
                            Weight = 7606.7m
                        },
                        new
                        {
                            ProductID = 24,
                            Color = "Red",
                            ListPrice = 1457.99m,
                            Name = "Road-450 Red, 48",
                            ProductCategoryID = 6,
                            ProductNumber = "BK-R68R-48",
                            Size = 48,
                            StandardCost = 884.7083m,
                            Weight = 7770m
                        },
                        new
                        {
                            ProductID = 25,
                            Color = "Red",
                            ListPrice = 1457.99m,
                            Name = "Road-450 Red, 52",
                            ProductCategoryID = 6,
                            ProductNumber = "BK-R68R-52",
                            Size = 52,
                            StandardCost = 884.7083m,
                            Weight = 7901.54m
                        },
                        new
                        {
                            ProductID = 26,
                            Color = "Red",
                            ListPrice = 782.99m,
                            Name = "Road-650 Red, 58",
                            ProductCategoryID = 6,
                            ProductNumber = "BK-R50R-58",
                            Size = 58,
                            StandardCost = 486.7066m,
                            Weight = 8976.55m
                        },
                        new
                        {
                            ProductID = 27,
                            Color = "Red",
                            ListPrice = 782.99m,
                            Name = "Road-650 Red, 60",
                            ProductCategoryID = 6,
                            ProductNumber = "BK-R50R-60",
                            Size = 60,
                            StandardCost = 486.7066m,
                            Weight = 9026.44m
                        },
                        new
                        {
                            ProductID = 28,
                            Color = "Red",
                            ListPrice = 782.99m,
                            Name = "Road-650 Red, 62",
                            ProductCategoryID = 6,
                            ProductNumber = "BK-R50R-62",
                            Size = 62,
                            StandardCost = 486.7066m,
                            Weight = 9071.8m
                        },
                        new
                        {
                            ProductID = 29,
                            Color = "Red",
                            ListPrice = 782.99m,
                            Name = "Road-650 Red, 44",
                            ProductCategoryID = 6,
                            ProductNumber = "BK-R50R-44",
                            Size = 44,
                            StandardCost = 486.7066m,
                            Weight = 8513.88m
                        },
                        new
                        {
                            ProductID = 30,
                            Color = "Red",
                            ListPrice = 782.99m,
                            Name = "Road-650 Red, 48",
                            ProductCategoryID = 6,
                            ProductNumber = "BK-R50R-48",
                            Size = 48,
                            StandardCost = 486.7066m,
                            Weight = 8677.18m
                        },
                        new
                        {
                            ProductID = 31,
                            Color = "Red",
                            ListPrice = 782.99m,
                            Name = "Road-650 Red, 52",
                            ProductCategoryID = 6,
                            ProductNumber = "BK-R50R-52",
                            Size = 52,
                            StandardCost = 486.7066m,
                            Weight = 8808.72m
                        },
                        new
                        {
                            ProductID = 32,
                            Color = "Black",
                            ListPrice = 782.99m,
                            Name = "Road-650 Black, 58",
                            ProductCategoryID = 6,
                            ProductNumber = "BK-R50B-58",
                            Size = 58,
                            StandardCost = 486.7066m,
                            Weight = 8976.55m
                        },
                        new
                        {
                            ProductID = 33,
                            Color = "Black",
                            ListPrice = 782.99m,
                            Name = "Road-650 Black, 60",
                            ProductCategoryID = 6,
                            ProductNumber = "BK-R50B-60",
                            Size = 60,
                            StandardCost = 486.7066m,
                            Weight = 9026.44m
                        },
                        new
                        {
                            ProductID = 34,
                            Color = "Black",
                            ListPrice = 782.99m,
                            Name = "Road-650 Black, 62",
                            ProductCategoryID = 6,
                            ProductNumber = "BK-R50B-62",
                            Size = 62,
                            StandardCost = 486.7066m,
                            Weight = 9071.8m
                        },
                        new
                        {
                            ProductID = 35,
                            Color = "Black",
                            ListPrice = 782.99m,
                            Name = "Road-650 Black, 44",
                            ProductCategoryID = 6,
                            ProductNumber = "BK-R50B-44",
                            Size = 44,
                            StandardCost = 486.7066m,
                            Weight = 8513.88m
                        },
                        new
                        {
                            ProductID = 36,
                            Color = "Black",
                            ListPrice = 782.99m,
                            Name = "Road-650 Black, 48",
                            ProductCategoryID = 6,
                            ProductNumber = "BK-R50B-48",
                            Size = 48,
                            StandardCost = 486.7066m,
                            Weight = 8677.18m
                        },
                        new
                        {
                            ProductID = 37,
                            Color = "Black",
                            ListPrice = 782.99m,
                            Name = "Road-650 Black, 52",
                            ProductCategoryID = 6,
                            ProductNumber = "BK-R50B-52",
                            Size = 52,
                            StandardCost = 486.7066m,
                            Weight = 8808.72m
                        },
                        new
                        {
                            ProductID = 38,
                            Color = "Silver",
                            ListPrice = 3399.99m,
                            Name = "Mountain-100 Silver, 38",
                            ProductCategoryID = 5,
                            ProductNumber = "BK-M82S-38",
                            Size = 38,
                            StandardCost = 1912.1544m,
                            Weight = 9230.56m
                        },
                        new
                        {
                            ProductID = 39,
                            Color = "Silver",
                            ListPrice = 3399.99m,
                            Name = "Mountain-100 Silver, 42",
                            ProductCategoryID = 5,
                            ProductNumber = "BK-M82S-42",
                            Size = 42,
                            StandardCost = 1912.1544m,
                            Weight = 9421.06m
                        },
                        new
                        {
                            ProductID = 40,
                            Color = "Silver",
                            ListPrice = 3399.99m,
                            Name = "Mountain-100 Silver, 44",
                            ProductCategoryID = 5,
                            ProductNumber = "BK-M82S-44",
                            Size = 44,
                            StandardCost = 1912.1544m,
                            Weight = 9584.36m
                        },
                        new
                        {
                            ProductID = 41,
                            Color = "Silver",
                            ListPrice = 3399.99m,
                            Name = "Mountain-100 Silver, 48",
                            ProductCategoryID = 5,
                            ProductNumber = "BK-M82S-48",
                            Size = 48,
                            StandardCost = 1912.1544m,
                            Weight = 9715.9m
                        },
                        new
                        {
                            ProductID = 42,
                            Color = "Black",
                            ListPrice = 3374.99m,
                            Name = "Mountain-100 Black, 38",
                            ProductCategoryID = 5,
                            ProductNumber = "BK-M82B-38",
                            Size = 38,
                            StandardCost = 1898.0944m,
                            Weight = 9230.56m
                        },
                        new
                        {
                            ProductID = 43,
                            Color = "Black",
                            ListPrice = 3374.99m,
                            Name = "Mountain-100 Black, 42",
                            ProductCategoryID = 5,
                            ProductNumber = "BK-M82B-42",
                            Size = 42,
                            StandardCost = 1898.0944m,
                            Weight = 9421.06m
                        },
                        new
                        {
                            ProductID = 44,
                            Color = "Black",
                            ListPrice = 3374.99m,
                            Name = "Mountain-100 Black, 44",
                            ProductCategoryID = 5,
                            ProductNumber = "BK-M82B-44",
                            Size = 44,
                            StandardCost = 1898.0944m,
                            Weight = 9584.36m
                        },
                        new
                        {
                            ProductID = 45,
                            Color = "Black",
                            ListPrice = 3374.99m,
                            Name = "Mountain-100 Black, 48",
                            ProductCategoryID = 5,
                            ProductNumber = "BK-M82B-48",
                            Size = 48,
                            StandardCost = 1898.0944m,
                            Weight = 9715.9m
                        },
                        new
                        {
                            ProductID = 46,
                            Color = "Black",
                            ListPrice = 1079.99m,
                            Name = "Mountain-300 Black, 38",
                            ProductCategoryID = 5,
                            ProductNumber = "BK-M47B-38",
                            Size = 38,
                            StandardCost = 598.4354m,
                            Weight = 11498.51m
                        },
                        new
                        {
                            ProductID = 47,
                            Color = "Black",
                            ListPrice = 1079.99m,
                            Name = "Mountain-300 Black, 40",
                            ProductCategoryID = 5,
                            ProductNumber = "BK-M47B-40",
                            Size = 40,
                            StandardCost = 598.4354m,
                            Weight = 11689.01m
                        },
                        new
                        {
                            ProductID = 48,
                            Color = "Black",
                            ListPrice = 1079.99m,
                            Name = "Mountain-300 Black, 44",
                            ProductCategoryID = 5,
                            ProductNumber = "BK-M47B-44",
                            Size = 44,
                            StandardCost = 598.4354m,
                            Weight = 11852.31m
                        },
                        new
                        {
                            ProductID = 49,
                            Color = "Black",
                            ListPrice = 1079.99m,
                            Name = "Mountain-300 Black, 48",
                            ProductCategoryID = 5,
                            ProductNumber = "BK-M47B-48",
                            Size = 48,
                            StandardCost = 598.4354m,
                            Weight = 11983.85m
                        },
                        new
                        {
                            ProductID = 50,
                            Color = "Red",
                            ListPrice = 2443.35m,
                            Name = "Road-250 Red, 44",
                            ProductCategoryID = 6,
                            ProductNumber = "BK-R89R-44",
                            Size = 44,
                            StandardCost = 1518.7864m,
                            Weight = 6699.52m
                        },
                        new
                        {
                            ProductID = 51,
                            Color = "Red",
                            ListPrice = 2443.35m,
                            Name = "Road-250 Red, 48",
                            ProductCategoryID = 6,
                            ProductNumber = "BK-R89R-48",
                            Size = 48,
                            StandardCost = 1518.7864m,
                            Weight = 6862.82m
                        },
                        new
                        {
                            ProductID = 52,
                            Color = "Red",
                            ListPrice = 2443.35m,
                            Name = "Road-250 Red, 52",
                            ProductCategoryID = 6,
                            ProductNumber = "BK-R89R-52",
                            Size = 52,
                            StandardCost = 1518.7864m,
                            Weight = 6994.36m
                        },
                        new
                        {
                            ProductID = 53,
                            Color = "Black",
                            ListPrice = 348.76m,
                            Name = "ML Mountain Frame - Black, 38",
                            ProductCategoryID = 16,
                            ProductNumber = "FR-M63B-38",
                            Size = 38,
                            StandardCost = 185.8193m,
                            Weight = 1238.3m
                        },
                        new
                        {
                            ProductID = 54,
                            Color = "Black",
                            ListPrice = 348.76m,
                            Name = "ML Mountain Frame - Black, 40",
                            ProductCategoryID = 16,
                            ProductNumber = "FR-M63B-40",
                            Size = 40,
                            StandardCost = 185.8193m,
                            Weight = 1256.44m
                        },
                        new
                        {
                            ProductID = 55,
                            Color = "Black",
                            ListPrice = 348.76m,
                            Name = "ML Mountain Frame - Black, 44",
                            ProductCategoryID = 16,
                            ProductNumber = "FR-M63B-44",
                            Size = 44,
                            StandardCost = 185.8193m,
                            Weight = 1274.59m
                        },
                        new
                        {
                            ProductID = 56,
                            Color = "Black",
                            ListPrice = 348.76m,
                            Name = "ML Mountain Frame - Black, 48",
                            ProductCategoryID = 16,
                            ProductNumber = "FR-M63B-48",
                            Size = 48,
                            StandardCost = 185.8193m,
                            Weight = 1292.73m
                        });
                });

            modelBuilder.Entity("ProductsAPI.Models.ProductCategory", b =>
                {
                    b.Property<int>("ProductCategoryID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProductCategoryID"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ProductCategoryID");

                    b.ToTable("ProductCategory");

                    b.HasData(
                        new
                        {
                            ProductCategoryID = 1,
                            Name = "Bikes"
                        },
                        new
                        {
                            ProductCategoryID = 2,
                            Name = "Components"
                        },
                        new
                        {
                            ProductCategoryID = 3,
                            Name = "Clothing"
                        },
                        new
                        {
                            ProductCategoryID = 4,
                            Name = "Accessories"
                        },
                        new
                        {
                            ProductCategoryID = 5,
                            Name = "Mountain Bikes"
                        },
                        new
                        {
                            ProductCategoryID = 6,
                            Name = "Road Bikes"
                        },
                        new
                        {
                            ProductCategoryID = 7,
                            Name = "Touring Bikes"
                        },
                        new
                        {
                            ProductCategoryID = 8,
                            Name = "Handlebars"
                        },
                        new
                        {
                            ProductCategoryID = 9,
                            Name = "Bottom Brackets"
                        },
                        new
                        {
                            ProductCategoryID = 10,
                            Name = "Brakes"
                        },
                        new
                        {
                            ProductCategoryID = 11,
                            Name = "Chains"
                        },
                        new
                        {
                            ProductCategoryID = 12,
                            Name = "Cranksets"
                        },
                        new
                        {
                            ProductCategoryID = 13,
                            Name = "Derailleurs"
                        },
                        new
                        {
                            ProductCategoryID = 14,
                            Name = "Forks"
                        },
                        new
                        {
                            ProductCategoryID = 15,
                            Name = "Headsets"
                        },
                        new
                        {
                            ProductCategoryID = 16,
                            Name = "Mountain Frames"
                        },
                        new
                        {
                            ProductCategoryID = 17,
                            Name = "Pedals"
                        },
                        new
                        {
                            ProductCategoryID = 18,
                            Name = "Road Frames"
                        },
                        new
                        {
                            ProductCategoryID = 19,
                            Name = "Saddles"
                        },
                        new
                        {
                            ProductCategoryID = 20,
                            Name = "Touring Frames"
                        },
                        new
                        {
                            ProductCategoryID = 21,
                            Name = "Wheels"
                        },
                        new
                        {
                            ProductCategoryID = 22,
                            Name = "Bib-Shorts"
                        },
                        new
                        {
                            ProductCategoryID = 23,
                            Name = "Caps"
                        },
                        new
                        {
                            ProductCategoryID = 24,
                            Name = "Gloves"
                        },
                        new
                        {
                            ProductCategoryID = 25,
                            Name = "Jerseys"
                        },
                        new
                        {
                            ProductCategoryID = 26,
                            Name = "Shorts"
                        },
                        new
                        {
                            ProductCategoryID = 27,
                            Name = "Socks"
                        },
                        new
                        {
                            ProductCategoryID = 28,
                            Name = "Tights"
                        },
                        new
                        {
                            ProductCategoryID = 29,
                            Name = "Vests"
                        },
                        new
                        {
                            ProductCategoryID = 30,
                            Name = "Bike Racks"
                        },
                        new
                        {
                            ProductCategoryID = 31,
                            Name = "Bike Stands"
                        },
                        new
                        {
                            ProductCategoryID = 32,
                            Name = "Bottles and Cages"
                        },
                        new
                        {
                            ProductCategoryID = 33,
                            Name = "Cleaners"
                        },
                        new
                        {
                            ProductCategoryID = 34,
                            Name = "Fenders"
                        },
                        new
                        {
                            ProductCategoryID = 35,
                            Name = "Helmets"
                        },
                        new
                        {
                            ProductCategoryID = 36,
                            Name = "Hydration Packs"
                        },
                        new
                        {
                            ProductCategoryID = 37,
                            Name = "Lights"
                        },
                        new
                        {
                            ProductCategoryID = 38,
                            Name = "Locks"
                        },
                        new
                        {
                            ProductCategoryID = 39,
                            Name = "Panniers"
                        },
                        new
                        {
                            ProductCategoryID = 40,
                            Name = "Pumps"
                        },
                        new
                        {
                            ProductCategoryID = 41,
                            Name = "Tires and Tubes"
                        });
                });

            modelBuilder.Entity("ProductsAPI.Models.Product", b =>
                {
                    b.HasOne("ProductsAPI.Models.ProductCategory", "ProductCategory")
                        .WithMany("Products")
                        .HasForeignKey("ProductCategoryID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProductCategory");
                });

            modelBuilder.Entity("ProductsAPI.Models.ProductCategory", b =>
                {
                    b.Navigation("Products");
                });
#pragma warning restore 612, 618
        }
    }
}
