@ProductsAPI_HostAddress = http://localhost:5289

GET {{ProductsAPI_HostAddress}}/productCategories/
Accept: application/json

GET {{ProductsAPI_HostAddress}}/productCategories/{id}
Accept: application/json

POST {{ProductsAPI_HostAddress}}/productCategories/
Accept: application/json

PUT {{ProductsAPI_HostAddress}}/productCategories/{id}
Accept: application/json

DELETE {{ProductsAPI_HostAddress}}/productCategories/{id}
Accept: application/json

###
